apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: microservices
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/version: "1.0.0"
    chaos-mesh-enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/version: "1.0.0"
        chaos-mesh-enabled: "true"
    spec:
      containers:
        - name: auth
          image: microservices-demo/auth:1.0.0
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://user:password@postgres-auth:5432/auth_db"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwt-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
