#!/usr/bin/env bash
# Resolves Vagrant's insecure_private_key for Ansible when Vagrantfile uses insert_key=false.
#
# Usage (from repository root):
#   source vagrant/ansible-ssh-env.sh
# Then:
#   ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/k3s-bootstrap.yml
#
# Or run (prints export line + writes vagrant/.ansible-ssh-env.generated):
#   bash vagrant/ansible-ssh-env.sh
#
# MODIFIED: Auto-detect WSL + Windows Vagrant profile path.

set -u

vagrant_ansible_resolve_ssh_key() {
  local candidates=()
  local p wu

  if [[ -n "${VAGRANT_INSECURE_KEY:-}" && -f "${VAGRANT_INSECURE_KEY}" ]]; then
    export VAGRANT_INSECURE_KEY
    return 0
  fi

  candidates+=("${HOME}/.vagrant.d/insecure_private_key")

  if [[ -f /proc/version ]] && grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
    candidates+=("/mnt/c/Users/${USER}/.vagrant.d/insecure_private_key")
    if command -v whoami.exe &>/dev/null; then
      wu="$(whoami.exe 2>/dev/null | tr -d '\r' | awk -F'\\' '{print $NF}')"
      [[ -n "${wu:-}" ]] && candidates+=("/mnt/c/Users/${wu}/.vagrant.d/insecure_private_key")
    fi
  fi

  for p in "${candidates[@]}"; do
    if [[ -f "$p" ]]; then
      export VAGRANT_INSECURE_KEY="$p"
      return 0
    fi
  done

  return 1
}

# MODIFIED: OpenSSH on WSL refuses private keys on Windows mounts (/mnt/c/...) when drvfs
# reports mode 0777. Copy into the WSL home filesystem and chmod 600.
vagrant_ansible_materialize_key_for_ssh() {
  local src dest
  src="${VAGRANT_INSECURE_KEY:?}"
  dest="${HOME}/.vagrant.d/insecure_private_key"

  if [[ "$src" == /mnt/* ]]; then
    mkdir -p "${HOME}/.vagrant.d"
    cp -f "$src" "$dest"
    chmod 600 "$dest"
    export VAGRANT_INSECURE_KEY="$dest"
    echo "Using WSL-local key at ${dest} (OpenSSH rejects loose perms on /mnt/c)." >&2
  else
    chmod 600 "$src" 2>/dev/null || true
  fi
}

vagrant_ansible_write_generated() {
  local out dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  out="${dir}/.ansible-ssh-env.generated"
  umask 077
  {
    echo "# Generated by vagrant/ansible-ssh-env.sh - do not commit"
    printf 'export VAGRANT_INSECURE_KEY=%q\n' "${VAGRANT_INSECURE_KEY}"
  } >"$out"
  chmod 600 "$out" 2>/dev/null || true
  echo "Wrote: $out" >&2
}

main() {
  if ! vagrant_ansible_resolve_ssh_key; then
    echo "Could not find Vagrant insecure_private_key. Install Vagrant, run 'vagrant up' once," >&2
    echo "or set VAGRANT_INSECURE_KEY to the full path of insecure_private_key." >&2
    return 1
  fi

  vagrant_ansible_materialize_key_for_ssh
  vagrant_ansible_write_generated

  if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    printf 'export VAGRANT_INSECURE_KEY=%q\n' "${VAGRANT_INSECURE_KEY}"
    echo "Tip: source vagrant/.ansible-ssh-env.generated in new shells before ansible-playbook." >&2
  else
    echo "VAGRANT_INSECURE_KEY=${VAGRANT_INSECURE_KEY}" >&2
  fi
  return 0
}

main
_status=$?
if [[ $_status -ne 0 ]]; then
  if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    exit "$_status"
  fi
  return "$_status" 2>/dev/null || exit "$_status"
fi

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  exit 0
fi
return 0 2>/dev/null || true
