[controller]
192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/controller/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[workers]
192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/worker1/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/worker2/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:children]
controller
workers
