apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: microservices
  labels:
    app.kubernetes.io/name: catalog
spec:
  selector:
    app.kubernetes.io/name: catalog
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP
