apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - route.yaml

patches:
# Remove the standard Ingress created in base, as we are using OpenShift Route.
- patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: frontend-ingress
      namespace: default

# Add OpenShift specific Security Context patches if needed
# For instance, some containers may need specific UID ranges or SCC handling,
# although most of these microservices run gracefully under the restricted SCC.
